apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bms-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
         http:
        paths:
          - path: /vijay
            pathType: Prefix
            backend:
              service:
                name: bms-service   # This must match your Service name
                port:
                  number: 80
